/// Shell scripts served to remote machines (Linux VMs etc.), embedded as strings
/// so the app stays a single self-contained binary.
enum EmbeddedScripts {
    /// Served at GET /install/hook — the bash hook remote machines run (needs curl + jq).
    static let hookScript = #"""
    #!/usr/bin/env bash
    # Notch hook for Claude Code (installed via the Notch app's /install endpoint).
    #   notch-hook.sh event       — fire-and-forget: report the hook event to the server
    #   notch-hook.sh permission  — PreToolUse: ask the server for an allow/deny decision
    # Fails open in every path so Claude Code falls back to its terminal flow.
    set -u

    MODE="${1:-event}"
    [ -f "$HOME/.notch/env" ] && . "$HOME/.notch/env"
    NOTCH_SERVER="${NOTCH_SERVER:-http://localhost:4519}"
    NOTCH_TOKEN="${NOTCH_TOKEN:-dev-token}"
    NOTCH_MACHINE="${NOTCH_MACHINE:-$(hostname -s)}"
    NOTCH_REMOTE_APPROVE="${NOTCH_REMOTE_APPROVE:-1}"

    payload="$(cat)" || exit 0
    command -v jq >/dev/null 2>&1 || exit 0
    command -v curl >/dev/null 2>&1 || exit 0

    body="$(jq -cn --arg machine "$NOTCH_MACHINE" --arg agent "claude-code" --argjson event "$payload" \
      '{machine: $machine, agent: $agent, ts: (now * 1000 | floor), event: $event}' 2>/dev/null)" || exit 0

    auth=(-H "Authorization: Bearer $NOTCH_TOKEN" -H "Content-Type: application/json")

    # Respect the session's permission mode: only gate tools Claude Code itself would
    # prompt for. Bypass/auto/dontAsk sessions are monitor-only; acceptEdits skips
    # the gate for edit tools but still gates Bash and plans.
    if [ "$MODE" = "permission" ]; then
      pm="$(jq -r '.permission_mode // "default"' <<<"$payload" 2>/dev/null)"
      tool="$(jq -r '.tool_name // ""' <<<"$payload" 2>/dev/null)"
      case "$pm" in
        bypassPermissions|auto|dontAsk) MODE="event" ;;
        acceptEdits) case "$tool" in Edit|Write|MultiEdit) MODE="event" ;; esac ;;
      esac
    fi

    if [ "$MODE" = "permission" ] && [ "$NOTCH_REMOTE_APPROVE" != "0" ]; then
      resp="$(curl -sS -m 3 "${auth[@]}" -d "$body" "$NOTCH_SERVER/api/permissions" 2>/dev/null)" || exit 0
      id="$(jq -r '.id // empty' <<<"$resp" 2>/dev/null)"
      [ -n "$id" ] || exit 0

      dec="$(curl -sS -m 58 -H "Authorization: Bearer $NOTCH_TOKEN" \
        "$NOTCH_SERVER/api/permissions/$id/decision?wait=55" 2>/dev/null)" || exit 0
      decision="$(jq -r '.decision // empty' <<<"$dec" 2>/dev/null)"
      reason="$(jq -r '.reason // "Decided via Notch"' <<<"$dec" 2>/dev/null)"

      case "$decision" in
        allow|deny)
          jq -cn --arg d "$decision" --arg r "$reason" \
            '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: $d, permissionDecisionReason: $r}}'
          ;;
      esac
      exit 0
    fi

    curl -sS -m 2 "${auth[@]}" -d "$body" "$NOTCH_SERVER/api/events" >/dev/null 2>&1
    exit 0
    """#

    /// Served at GET /install — self-configuring installer for a remote machine.
    /// __SERVER__ and __TOKEN__ are substituted per request.
    static let installScript = #"""
    #!/bin/bash
    # Notch remote-machine setup (generated by the Notch app)
    set -euo pipefail

    for dep in curl jq; do
      command -v "$dep" >/dev/null 2>&1 || {
        echo "error: $dep is required (install it: apt install $dep / brew install $dep)" >&2
        exit 1
      }
    done

    mkdir -p "$HOME/.notch" "$HOME/.claude"

    curl -fsS "__SERVER__/install/hook?token=__TOKEN__" -o "$HOME/.notch/notch-hook.sh"
    chmod 755 "$HOME/.notch/notch-hook.sh"

    if [ ! -f "$HOME/.notch/env" ]; then
      cat > "$HOME/.notch/env" <<EOF
    NOTCH_SERVER="__SERVER__"
    NOTCH_TOKEN="__TOKEN__"
    NOTCH_MACHINE="$(hostname -s)"
    NOTCH_REMOTE_APPROVE=1
    EOF
      echo "wrote $HOME/.notch/env"
    else
      echo "kept existing $HOME/.notch/env"
    fi

    SETTINGS="$HOME/.claude/settings.json"
    [ -f "$SETTINGS" ] || echo '{}' > "$SETTINGS"
    cp "$SETTINGS" "$SETTINGS.notch-backup"

    HOOK_CMD_EVENT='"$HOME/.notch/notch-hook.sh" event'
    HOOK_CMD_PERM='"$HOME/.notch/notch-hook.sh" permission'

    jq --arg ev "$HOOK_CMD_EVENT" --arg perm "$HOOK_CMD_PERM" '
      def strip: map(select(((.hooks // []) | any(.command // "" | contains("notch-hook"))) | not));
      .hooks = (.hooks // {})
      | .hooks.SessionStart      = (((.hooks.SessionStart // [])      | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.UserPromptSubmit  = (((.hooks.UserPromptSubmit // [])  | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.Notification      = (((.hooks.Notification // [])      | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.PostToolUse       = (((.hooks.PostToolUse // [])       | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.Stop              = (((.hooks.Stop // [])              | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.SessionEnd        = (((.hooks.SessionEnd // [])        | strip) + [{hooks: [{type: "command", command: $ev}]}])
      | .hooks.PreToolUse        = (((.hooks.PreToolUse // [])        | strip) + [{matcher: "Bash|Write|Edit|MultiEdit|ExitPlanMode", hooks: [{type: "command", command: $perm, timeout: 60}]}])
    ' "$SETTINGS" > "$SETTINGS.tmp" && mv "$SETTINGS.tmp" "$SETTINGS"

    echo "done — new Claude Code sessions on this machine report to __SERVER__"
    """#
}
